/* Generated By:JavaCC: Do not edit this line. AnansiTreeConstants.java Version 5.0 */
package javacc;

public interface AnansiTreeConstants
{
  public int JJTPROGRAMA = 0;
  public int JJTFUNCT_LIST = 1;
  public int JJTFUNCT_DECL = 2;
  public int JJTPARAM_LIST = 3;
  public int JJTVAR_LIST = 4;
  public int JJTFUNCT_TYPE = 5;
  public int JJTFUNCT_BODY = 6;
  public int JJTRETURN = 7;
  public int JJTIF = 8;
  public int JJTSWITCH = 9;
  public int JJTFOR = 10;
  public int JJTWHILE = 11;
  public int JJTATRIBUICAO = 12;
  public int JJTEXPRESSAO = 13;
  public int JJTNUMERO_EXPRESSAO = 14;
  public int JJTTERM = 15;
  public int JJTUNARY_EXPR = 16;
  public int JJTFACTOR = 17;


  public String[] jjtNodeName = {
    "PROGRAMA",
    "FUNCT_LIST",
    "FUNCT_DECL",
    "PARAM_LIST",
    "VAR_LIST",
    "FUNCT_TYPE",
    "FUNCT_BODY",
    "RETURN",
    "IF",
    "SWITCH",
    "FOR",
    "WHILE",
    "ATRIBUICAO",
    "EXPRESSAO",
    "NUMERO_EXPRESSAO",
    "TERM",
    "UNARY_EXPR",
    "FACTOR",
  };
}
/* JavaCC - OriginalChecksum=a64ffe93e21902e7c2c940283eba9a1c (do not edit this line) */
